apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment-server.yaml
  - manifests/service-server.yaml
  - manifests/autoscaler-server.yaml
images:
  - name: PROJECT/IMAGE
    newName: anttitmh/server