apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: argo-cpu
  namespace: project
spec:
  metrics:
  - name: cpu
    initialDelay: 10m
    successCondition: result < 0.7
    provider:
      prometheus:
        address: 10.42.2.6:9090
        query: |
          scalar(sum(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="project"}[1m]))))