apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER_IMAGE
          imagePullPolicy: Always
          env: 
          - name: NATS_URL
            value: nats://my-nats:4222
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegramsecret
                key: TELEGRAM_TOKEN
          - name: CHANNEL_ID          
            value: '-1614530705'
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"