apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: broadcaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/IMAGE
          imagePullPolicy: Always
          env: 
          - name: NATS_URL
            value: nats:4222
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegramsecret
                key: TELEGRAM_TOKEN
          - name: CHANNEL_ID          
            value: '-1614530705'