apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pong-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80