apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: argo-cpu
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anttitmh/frontend
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"