apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-ss
spec:
  serviceName: postgres-svc
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - name: web
              containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: app
          - name: POSTGRES_USER
            value: appuser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsecret
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 100Mi