apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/secret.yaml
  - manifests/deployment-server.yaml
  - manifests/service-server.yaml
  - manifests/autoscaler-server.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/autoscaler.yaml
  - manifests/ingress.yaml
  - manifests/secret-telegram.yaml
  - manifests/deployment-broadcaster.yaml
  - manifests/analysistemplate.yaml
images:
- name: FRONT_IMAGE
  newName: anttitmh/frontend
- name: SERVER_IMAGE
  newName: anttitmh/Server
- name: BROADCASTER_IMAGE
  newName: anttitmh/broadcaster