apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/secret.yaml
- manifests/deployment-server.yaml
- manifests/service-server.yaml
- manifests/autoscaler-server.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/autoscaler.yaml
- manifests/ingress.yaml
- manifests/secret-telegram.yaml
- manifests/deployment-broadcaster.yaml
- manifests/analysistemplate.yaml
images:
- name: BROADCASTER_IMAGE
  newName: anttitmh/broadcaster
  newTag: f575c02c4624bfe8cc75fd84a5801552e81c8734
- name: FRONT_IMAGE
  newName: anttitmh/frontend
  newTag: f575c02c4624bfe8cc75fd84a5801552e81c8734
- name: SERVER_IMAGE
  newName: anttitmh/server
  newTag: f575c02c4624bfe8cc75fd84a5801552e81c8734
