apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: anttitmh/pong
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
          