apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - name: default
      port: 1234
      protocol: TCP
      targetPort: 3001
