apiVersion: v1
kind: Service
metadata:
  name: pong-svc
spec:
  type: ClusterIP
  selector:
    app: pong
  ports:
    - name: default
      port: 1234
      protocol: TCP
      targetPort: 3001
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001