apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:  
          containers:
          - name: todo
            image: anttitmh/cron
            env:
              - name: URL
                value: "https://en.wikipedia.org/wiki/Special:Random"
          restartPolicy: Never