apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: anttitmh/server
          readinessProbe:
           initialDelaySeconds: 10
           periodSeconds: 60
           httpGet:
             path: /healthz
             port: 3001       
          livenessProbe:
            initialDelaySeconds: 100
            periodSeconds: 60
            httpGet:
               path: /healthz
               port: 3001
          envFrom:
            - secretRef:
                name: pgsecret
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
